use titulacion;

insert into tipo_usuario(nombre) values
	('Administrador'),
    ('Jefe de Dtpo'),
    ('Alumno');
    
-- select * from tipo_usuario;

insert into usuario(nombre, correo, contrasena, id_tipo_usuario)
values
('Juan', 'juan@mail.com', 'ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f', 1);

-- select * from usuario;

insert into departamento(nombre) values
	('Departamento de Sistemas y Computacion'),
    ('Departamento de Ingeniería Industrial'),
    ('Departamento de Ciencas Económico Administrativas'),
    ('Departamento de Ciencias de la Tierra'),
    ('Departamento de Ingeniería Química y Bioquímica');
    
-- select * from departamento;
    
INSERT INTO docente(id_dpto, nombre, titulo, diminutivo, cedula)
VALUES 
(4, 'ABEL PÉREZ RODRÍGUEZ', 'INGENIERO CIVIL', 'ING.', '1577455'),
(2, 'ABRAHAM ANDRADE ÁVALOS', 'INGENIERO INDUSTRIAL EN QUÍMICA', 'ING.', '2385733'),
(3, 'ADRIANA MONROY CARRERA', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '2902837'),
(1, 'ALEJANDRA PAULINA MENDOZA CEJA', 'MAESTRÍA EN EDUCACIÓN', 'MTRA.', '12922526'),
(4, 'ALEJANDRO ARCEO HERNÁNDEZ', 'ARQUITECTO', 'ARQ.', '6366794'),
(2, 'ALEJANDRO CÉSAR AYALA OLIVERA', 'INGENIERO INDUSTRIAL', 'ING.', '2869758'),
(4, 'ALEJANDRO RAMÍREZ ALVARADO', 'INGENIERO INDUSTRIAL', 'ING.', '3515663'),
(4, 'ALFONSO HIGAREDA RUIZ', 'INGENIERO BIOQUÍMICO', 'ING.', '1069061'),
(2, 'ALFREDO OROPEZA SOTO', 'INGENIERO INDUSTRIAL EN ELÉCTRICA', 'ING.', '415102'),
(1, 'ALICIA VERÓNICA FLORES HIGAREDA', 'MAESTRÍA EN EDUCACIÓN', 'MTRA.', '10501095'),
(1, 'AMELIA VARAJAS RÍOS', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1221920'),
(5, 'ANA ESTHER JIMÉNEZ ALONSO', 'DOCTORA EN CIENCIAS EN AGROBIOTECNOLOGÍA', 'DRA.', '8151668'),
(1, 'ANA ROSA MACÍAS LÓPEZ', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1350284'),
(4, 'ANA ROSA SÁNCHEZ MANZO', 'INGENIERO BIOQUÍMICO', 'ING.', '5801383'),
(1, 'ANDRÉS DOMINGO VIERA LÓPEZ', 'INGENIERO EN ELECTRÓNICA', 'ING.', '4738396'),
(4, 'ANDRÉS ELOY GONZÁLEZ VEGA', 'ARQUITECTO', 'ARQ.', '3620205'),
(1, 'ANDRÉS LÓPEZ VALDOVINOS', 'MAESTRÍA EN CIENCIAS EN ADMINISTRACIÓN', 'MTRO.', '6037318'),
(4, 'ARMANDO ÁVALOS ARCEO', 'INGENIERO BIOQUÍMICO EN ALIMENTOS', 'ING.', '1169840'),
(3, 'ARMANDO HERNÁNDEZ GÁLVEZ', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '2434205'),
(2, 'ARTURO CUELLAR SANTANA', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '7194396'),
(1, 'ARTURO GUZMÁN RUIZ', 'MAESTRO EN EDUCACIÓN', 'MTRO.', '7506979'),
(3, 'BENJAMÍN RENTERÍA VILLA', 'LICENCIADO EN RELACIONES INDUSTRIALES', 'LIC.', '2351070'),
(1, 'BERTHA ALICIA SÁNCHEZ URBINA', 'MAESTRÍA EN EDUCACIÓN', 'MTRA.', '10171875'),
(1, 'CARLA GABRIELA VARGAS VÁZQUEZ', 'MAESTRÍA EN CIENCIAS EN PRODUCCIÓN AGRÍCOLA SUSTENTABLE', 'MTRA.', '11467855'),
(4, 'CARLOS FLORES GALLEGOS', 'INGENIERO CIVIL', 'ING.', '4208322'),
(2, 'CARLOS IGNACIO CANO MUÑIZ', 'INGENIERO INDUSTRIAL', 'ING.', '7270715'),
(2, 'CLAUDIO ARREDONDO CERVANTES', 'INGENIERO INDUSTRIAL', 'ING.', '4611535'),
(3, 'CUAUHTÉMOC SUÁREZ GONZÁLEZ', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC.', '1415030'),
(2, 'DANIEL GIL CEDEÑO', 'INGENIERO INDUSTRIAL EN SIDERURGIA', 'ING.', '1853317'),
(1, 'DAVID LIRA LEYVA', 'INGENIERO EN SISTEMAS', 'ING.', '2224882'),
(4, 'EDGAR VINICIO VILLALPANDO ARTEAGA', 'DOCTOR EN CIENCIA Y TECNOLOGÍA EN BIOTECNOLOGÍA PRODUCTIVA', 'DR.', '09071718'),
(3, 'EDNA PAOLA CHÁVEZ GUERRA', 'MAESTRA EN ADMINISTRACIÓN', 'MTRA.', '5713619'),
(1, 'EDUARDO HERNÁNDEZ SANDOVAL', 'MAESTRÍA EN CIENCIAS EN ADMINISTRACIÓN', 'MTRO.', '4524290'),
(1, 'EDUARDO LUNA MAGALLÁN', 'LICENCIADO EN CONTADURÍA', 'LIC.', '2389622'),
(2, 'EDUARDO POO CHÁVEZ', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2331963'),
(5, 'EDUARDO VILLASEÑOR GUTIÉRREZ', 'MÉDICO CIRUJANO Y PARTERO', 'MCYP', '1170856'),
(3, 'ENRIQUE PÉREZ RODRÍGUEZ', 'MAESTRÍA EN VALUACIÓN', 'MTRO.', '4315469'),
(1, 'ERICK DALET VILLANUEVA MASCORT', 'INGENIERO EN SISTEMAS COMPUTACIONALES', 'ING.', '4419945'),
(4, 'ERNESTO OREGEL ZAMUDIO', 'INGENIERO BIOQUÍMICO', 'ING.', '6838665'),
(1, 'ESMERALDA SELENE OSEGUERA CAMACHO', 'MAESTRÍA EN EDUCACIÓN', 'MTRA.', '10054078'),
(3, 'ESTHELA CASTELLÓN PLASCENCIA', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC.', '1578863'),
(1, 'FABIOLA OCHOA VILLASEÑOR', 'MAESTRÍA EN EDUCACIÓN', 'MTRA.', '12835124'),
(1, 'FERNANDO CARRANZA CAMPOS', 'INGENIERO EN SISTEMAS COMPUTACIONALES EN PROGRAMACIÓN', 'ING.', '2154151'),
(2, 'FERNANDO VARGAS GUERRA', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2811239'),
(3, 'FIDEL LOMELÉ ÁLVAREZ', 'CONTADOR PÚBLICO', 'C. P.', '1066475'),
(4, 'FLAVIO MARTÍNEZ AGUILERA', 'MAESTRÍA EN CIENCIAS EN PRODUCCIÓN AGRÍCOLA SUSTENTABLE', 'MTRO.', '11564905'),
(4, 'FLORIÁN DE JESÚS RODRÍGUEZ CONTRERAS', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1180342'),
(2, 'FRANCISCO AGUSTÍN GARCÍA LEAL', 'INGENIERO QUÍMICO', 'ING.', '2838557'),
(1, 'FRANCISCO ARMANDO PAYÁN GUERRERO', 'INGENIERO EN ELECTRÓNICA', 'ING.', '3093466'),
(2, 'FRANCISCO CAZAREZ YEPEZ', 'INGENIERO INDUSTRIAL EN QUÍMICA', 'ING.', '2812641'),
(3, 'FRANCISCO JAVIER PO CHÁVEZ', 'MATEMÁTICO', 'MAT.', '444225'),
(1, 'FRANCISCO MÉNDEZ GUDIÑO', 'MAESTRO EN IMPUESTOS', 'MTRO.', '8632092'),
(3, 'GABRIEL ARTURO CHÁVEZ NÚÑEZ', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '2614869'),
(1, 'GASTÓN EDUARDO GRACIDA JUÁREZ', 'MAESTRÍA EN FINANZAS', 'MTRO', '7850682'),
(3, 'GAUDENCIO MONDRAGÓN GARCÍA', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC. ', '1219824'),
(2, 'GERMAN ULISES MARTÍNEZ AGUILERA', 'INGENIERO INDUSTRIAL', 'ING.', '6798955'),
(4, 'GLORIA DEL ROCÍO ÁVALOS SÁNCHEZ', 'INGENIERO BIOQUÍMICO', 'ING.', '5801399'),
(2, 'GLORIA PEÑA RAMOS', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '3914180'),
(3, 'GREGORIO MANZO CANELA', 'INGENIERO BIOQUÍMICO', 'ING.', '591339'),
(4, 'GUADALUPE OYOQUE SALCEDO', 'INGENIERO BIOQUÍMICO', 'ING.', '4201182'),
(5, 'HERMES LÓPEZ DEL RÍO', 'ARQUITECTO', 'ARQ.', '1919822'),
(3, 'IGNACIO MORENO HIGAREDA', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC.', '517314'),
(2, 'IGNACIO OROPEZA SOTO', 'INGENIERO INDUSTRIAL MECÁNICA EN DISEÑO', 'ING.', '1262460'),
(2, 'IRMA PARTIDA CERVANTES', 'INGENIERO INDUSTRIAL EN QUÍMICA', 'ING.', '2335203'),
(2, 'J. DOLORES GARCÍA DANIEL', 'INGENIERO MECÁNICO', 'ING.', '1435086'),
(1, 'J. JESÚS ÁLVAREZ SANTILLÁN', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3139943'),
(2, 'J. JESÚS MENDOZA OCHOA', 'INGENIERO INDUSTRIAL EN QUÍMICA', 'ING.', '1169611'),
(2, 'J. JESÚS VIERA CAMACHO', 'INGENIERO INDUSTRIAL EN ELÉCTRICA', 'ING.', '1985280'),
(5, 'J. JESÚS VILLASEÑOR MAGALLÁN', 'ARQUITECTO', 'ARQ.', '757433'),
(1, 'J. TIMOTEO HERNÁNDEZ ÁLVAREZ', 'MAESTRÍA EN INGENIERÍA CON ESPECIALIDAD EN INVESTIGACIÓN DE OPERACIONES', 'M. I. ', '7155584'),
(3, 'JAIME SANTILLÁN CÁRDENAS', 'LICENCIADO EN CIENCIAS Y TÉCNICAS DE LA COMUNICACIÓN', 'LIC.', '3241957'),
(1, 'JAVIER ALEJANDRO BACA LÓPEZ', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3064962'),
(3, 'JESÚS ORDAZ CEJA', 'LICENCIADO EN ADMINISTRACIÓN', 'LIC.', '3139688'),
(4, 'JESÚS RICARDO GONZÁLEZ GALARZA', 'MAESTRO EN ADMINISTRACIÓN', 'MTRO.', '5192199'),
(4, 'JOEL GUERRA PIZANO', 'MAESTRÍA EN CIENCIAS EN PRODUCCIÓN AGRÍCOLA SUSTENTABLE', 'MTRO.', '10598165'),
(1, 'JORGE ALBERTO RIVERA GUERRA', 'INGENIERO EN SISTEMAS COMPUTACIONALES', 'ING.', '2640794'),
(4, 'JORGE ALBERTO SÁNCHEZ CEJA', 'INGENIERO CIVIL', 'ING.', '4413784'),
(5, 'JORGE ARMANDO NÚÑEZ ALFARO', 'ARQUITECTO', 'ARQ.', '4717238'),
(2, 'JORGE CANELA GÓMEZ', 'INGENIERO INDUSTRIAL QUÍMICO', 'ING.', '2811235'),
(1, 'JOSÉ ANTONIO CEJA DÍAZ', 'MAESTRÍA EN CIENCIAS EN CIENCIAS COMPUTACIONALES', 'M. C.', '4388088'),
(3, 'JOSÉ FLORES LICEA', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1853458'),
(4, 'JOSÉ GUADALUPE VALLARTA MAGALLÓN', 'LICENCIADO EN DERECHO Y CIENCIAS', 'LIC.', '1528173'),
(2, 'JOSÉ GUIMEL VILLANUEVA MASCORT', 'MAESTRÍA EN EDUCACIÓN', 'MTRO.', '09571406'),
(3, 'JOSÉ HUMBERTO CARRANZA GARCÍA', 'INGENIERO BIOQUÍMICO', 'ING.', '9037904'),
(5, 'JOSÉ LUIS ANAYA MURATALLA', 'MAESTRO EN CIENCIAS EN ARQUITECTURA', 'M. C.', '7232885'),
(3, 'JOSÉ LUIS MÉNDEZ GRANADOS', 'MAESTRÍA EN CIENCIAS EN ADMINISTRACIÓN', 'MTRO.', '6099399'),
(4, 'JOSÉ MANUEL PADILLA AGUILAR', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '4930549'),
(4, 'JOSÉ MANUEL VALENCIA MANZO', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1553903'),
(5, 'JOSÉ ODISEO LÓPEZ CALDERÓN', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '2811678'),
(5, 'JOSÉ TRINIDAD ROMÁN CHÁVEZ', 'ARQUITECTO', 'ARQ.', '3559633'),
(3, 'JOSEFINA BAUTISTA RODRÍGUEZ', 'MAESTRÍA EN ADMINISTRACIÓN', 'M. A.', '6713176'),
(2, 'JUAN CARLOS BARRAGÁN BARAJAS', 'MAESTRÍA EN CIENCIAS EN ADMINISTRACIÓN', 'MTRO.', '6037305'),
(2, 'JUAN CARLOS CANELA GÓMEZ', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1985351'),
(2, 'JUAN CARLOS GUTIÉRREZ CASTELLANOS', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1180407'),
(2, 'JUAN GERARDO MUÑOZ OROZCO', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1635590'),
(3, 'JUAN LUIS HERNÁNDEZ GARCÍA', 'INGENIERO INDUSTRIAL', 'ING.', '2766836'),
(5, 'JUAN MANUEL GUERRERO NAVARRETE', 'ARQUITECTO', 'ARQ.', '3590673'),
(3, 'JUAN MANUEL GUTIÉRREZ SÁNCHEZ', 'LICENCIADO EN BIOLOGÍA', 'L. B.', '2935805'),
(3, 'JUAN MANUEL HERNÁNDEZ AMEZCUA', 'LICENCIADO EN DERECHO', 'LIC.', '1550538'),
(1, 'JUAN PEDRO QUIÑONES REYES', 'DOCTOR EN INGENIERIA EN EL ÁREA DE MECATRÓNICA', 'DR.', '7452041'),
(5, 'JULIO CEJA DÍAZ', 'LICENCIADO EN DERECHO', 'LIC.', '2629973'),
(5, 'KATYA NOEMÍ NAVARRO GARCÍA', 'ARQUITECTO', 'ARQ.', '7272753'),
(1, 'LAURA GUADALUPE ÁVILA NOVOA', 'MAESTRÍA EN FINANZAS', 'MTRA.', '8446464'),
(1, 'LEONARDO MARTÍNEZ GONZÁLEZ', 'INGENIERO EN SISTEMAS COMPUTACIONALES EN PROGRAMACIÓN', 'ING.', '2388768'),
(4, 'LUIS ANTONIO DÍAZ ROSALES', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '4158275'),
(4, 'LUIS FERNANDO MIRELES GUERRERO', 'MAESTRÍA EN VALUACIÓN', 'M. V.', '9763656'),
(5, 'LUIS HUMBERTO GONZÁLEZ HERNÁNDEZ', 'MAESTRÍA EN CIENCIAS EN PRODUCCIÓN AGRÍCOLA SUSTENTABLE', 'MTRO.', '11463025'),
(2, 'LUIS IREPAN NÚÑEZ', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '3139926'),
(1, 'LUZ MARÍA NOVOA GARCÍA', 'MAESTRÍA EN ADMINISTRACIÓN CON ESPECIALIDAD EN FINANZAS', 'M. A.', '3225568'),
(3, 'MA. DE JESÚS FLORES FRANCO', 'MAESTRÍA EN CIENCIAS EN ENSEÑANZA DE LAS CIENCIAS', 'M. C.', '5885227'),
(3, 'MA. DE JESÚS MAGALLÓN FARIAS', 'MAESTRÍA EN CIENCIAS EN ADMINISTRACIÓN', 'M. C.', '5181477'),
(5, 'MA. DOLORES GARCÍA CÁRDENAS', 'MAESTRÍA EN TERAPIA GESTALT', 'MTG.', '10214042'),
(4, 'MA. TERESA CASTILLO CASTILLO', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1223579'),
(1, 'MA. VIRGINIA BAUTISTA MANZO', 'INGENIERO BIOQUÍMICO', 'ING.', '1076307'),
(2, 'MANUEL DE JESÚS ARJONA PÉREZ', 'MAESTRO EN CIENCIAS EN INGENIERÍA MECÁNICA', 'MTRO.', '4905405'),
(3, 'MARCELA ALESSANDRINA ARTEAGA HERRERA', 'INGENIERO BIOQUÍMICO EN ALIMENTOS', 'ING.', '1552021'),
(2, 'MARCO ANTONIO CAMPUZANO GARCÍA', 'INGENIERO BIOQUÍMICO', 'ING.', '3021640'),
(3, 'MARÍA DEL CARMEN NAVA ROJAS', 'MAESTRÍA EN CIENCIAS EN ENSEÑANZA DE LAS CIENCIAS', 'M. C.', '5500609'),
(4, 'MARÍA DEL SOCORRO HERLINDA OLIVERA GUARNERO', 'LICENCIADO EN HISTORIA', 'LIC.', '659509'),
(1, 'MARÍA ELENA CABRERA ROCHA', 'MAESTRÍA EN CIENCIAS EN ENSEÑANZA DE LAS CIENCIAS', 'M. C.', '4439574'),
(1, 'MARÍA EUGENIA SEGURA MENDOZA', 'MAESTRÍA EN CIENCIAS EN CIENCIAS COMPUTACIONALES', 'M. C.', '3142989'),
(3, 'MARÍA GARCÍA HERNÁNDEZ', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC.', '2071573'),
(4, 'MARÍA YOLANDA GUZMÁN MUÑOZ', 'LICENCIADO EN CONTADURÍA', 'LIC.', '2811621'),
(3, 'MARTHA ELENA GARCÍA GUTIÉRREZ', 'LICENCIADO EN RELACIONES COMERCIALES', 'LIC.', '1674947'),
(1, 'MARTHA ELIZABETH GONZÁLEZ ZEPEDA', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3112302'),
(1, 'MARTHA PATRICIA MÉNDEZ ROCHA', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3389390'),
(2, 'MARTÍN CORONA SÁNCHEZ', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1063005'),
(2, 'MARTÍN HURTADO AVIÑA', 'LICENCIADO EN ADMINISTRACIÓN INDUSTRIAL', 'LIC.', '1504670'),
(1, 'MARTÍN VALENCIA', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3750593'),
(1, 'MARTINA ELOISA SANTILLÓN FRAGOZA', 'MAESTRÍA EN TERAPIA GESTALT', 'MTG.', '4269231'),
(1, 'MAYRA IBETH MEJÍA POZOS', 'MAESTRÍA EN DESARROLLO ORGANIZACIONAL Y HUMANO', 'MTRA.', '6910076'),
(1, 'MIGUEL ÁNGEL PAZ OSEGUERA', 'MAESTRÍA EN CALIDAD TOTAL Y COMPETITIVIDAD', 'MTRO.', '5688815'),
(1, 'MIGUEL PERALTA LÁZARO', 'MAESTRO EN CIENCIAS EN ADMINISTRACIÓN', 'M. C.', '6099407'),
(1, 'MOISÉS ARREDONDO OLLOQUI', 'MAESTRO EN CIENCIAS EN ADMINISTRACIÓN', 'MTRO.', '7421857'),
(1, 'MÓNICA GUADALUPE CONTRERAS HIGAREDA', 'DOCTORADO EN CIENCIAS DE LA EDUCACIÓN', 'DRA.', '13121078'),
(2, 'MÓNICA YADIRA EDITH FLORES CASTILLO', 'LICENCIADO EN SISTEMAS COMPUTACIONALES', 'LIC.', '3867532'),
(1, 'NAHUM CASTELLANOS PÉREZ', 'DOCTOR EN CIENCIAS EN AGROBIOTECNOLOGÍA', 'DR.', '8151667'),
(1, 'OCTAVIO RAMÍREZ ROJAS', 'DOCTORADO EN INFORMÁTICA', 'DR.', '5777008'),
(1, 'OTHONIEL RIVERA MÉNDEZ', 'MAESTRO EN EDUCACIÓN', 'MTRO.', '7180299'),
(1, 'PATRICIA HIGAREDA AMEZCUA', 'ARQUITECTO', 'ARQ.', '5320092'),
(1, 'PEDRO HERNÁNDEZ RODRÍGUEZ', 'LICENCIADO EN RELACIONES INDUSTRIALES', 'LIC.', '614433'),
(2, 'RAÚL FLORES GARCÍA', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '1806562'),
(3, 'RICARDO GRANADOS ÁVILA', 'MAESTRO EN EDUCACIÓN', 'MTRO.', '7506978'),
(1, 'RICARDO LUNA MAGALLÓN', 'MAESTRÍA EN FISCAL', 'M. F.', '5175469'),
(2, 'RICARDO MÉNDEZ CABEZAS', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2653956'),
(2, 'RICARDO MOLINA FUENTES', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2529336'),
(3, 'RICARDO MURGUÍA RIVAS', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3021741'),
(1, 'RICARDO SILVA TORRES', 'INGENIERO ARQUITECTO', 'ING. ARQ.', '1318751'),
(1, 'ROBERTO ÁVALOS CASTILLO', 'MAESTRÍA EN FISCAL', 'M. F.', '6515643'),
(2, 'ROBERTO LEYVA ALVARADO', 'INGENIERO INDUSTRIAL QUÍMICO', 'ING.', '1635425'),
(1, 'RODOLFO ORTEGA TIBURCIO', 'ARQUITECTO', 'ARQ.', '1812111'),
(1, 'RODRIGO ÁVILA VÍCTOR', 'ARQUITECTO', 'ARQ.', '2554221'),
(1, 'RODRIGO SÁNCHEZ ZEPEDA', 'ARQUITECTO', 'ARQ.', '4444062'),
(2, 'ROMÁN MILLÁN HERNÁNDEZ', 'INGENIERO MECÁNICO ELECTRICISTA', 'ING.', '1327592'),
(1, 'ROSALÍA ELVIA PÉREZ PEREDA', 'MAESTRO EN CIENCIAS EN ENSEÑANZA DE LAS CIENCIAS', 'MTRO.', '4437761'),
(1, 'SALVADOR ÁVILA SALCEDO', 'INGENIERO QUÍMICO INDUSTRIAL', 'ING.', '903232'),
(1, 'SALVADOR GODOY MENDOZA', 'INGENIERO ARQUITECTO', 'ING. ARQ.', '2363800'),
(1, 'SALVADOR GUERRA VARGAS', 'INGENIERO INDUSTRIAL QUÍMICO', 'ING.', '1421028'),
(1, 'SALVADOR TOLENTO CEJA', 'CONTADOR PÚBLICO', 'C. P.', '1216460'),
(1, 'SAMUEL SEGURA BAUTISTA', 'LICENCIADO EN DERECHO', 'LIC.', '1225915'),
(1, 'SANDRA LUZ MALDONADO LÓPEZ', 'MAESTRA EN TERAPIA GESTALT', 'MTRA.', '4434123'),
(1, 'SUSANA FLORES OCHOA', 'LICENCIADO EN INFORMÁTICA', 'LIC.', '3295409'),
(1, 'SUSANA JANET SANTOYO MURGUÍA', 'MAESTRÍA EN CIENCIAS EN PRODUCCIÓN AGRÍCOLA SUSTENTABLE', 'MTRA.', '11463014'),
(2, 'UBERTINO GERARDO ALEJO ESCUTIA', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2015995'),
(2, 'VICENTE CAMPOS CONTRERAS', 'INGENIERO INDUSTRIAL EN PRODUCCIÓN', 'ING.', '2726181'),
(1, 'VÍCTOR MANUEL MELGOZA OCHOA', 'LICENCIADO EN DERECHO', 'LIC.', '400705'),
(1, 'XÓCHITL GONZÁLEZ CARRILLO', 'MAESTRÍA EN DESARROLLO ORGANIZACIONAL Y HUMANO', 'MTRA.', '6429207'),
(1, 'YOLANDA GARCÍA CÁRDENAS', 'LICENCIADO EN CONTADURÍA', 'LIC.', '1709767');

-- select * from docente;

-- select * from carrera;

insert into carrera(nombre, id_dpto)
value
('Ingenieria en sistemas computacionales', 1),
('Ingenieria en Bioquimica', 5),
('Ingenieria en Arquitectura', 4),
('Contaduria', 3),
('Ingenieria en Administracion', 3),
('Ingenieria Industrial', 2),
('Ingenieria en Gestión', 2);

INSERT INTO ALTERNATIVA(ALTERNATIVA, hab)
VALUES('ALTERNATIVA A PROMEDIO GENERAL DE 95 A 100', 1);

INSERT INTO ALTERNATIVA(ALTERNATIVA, hab)
VALUES('ALTERNATIVA B PRESENTACIÓN Y DEFENSA DEL PROYECTO', 1);

INSERT INTO ALTERNATIVA(ALTERNATIVA, hab)
VALUES('DESEMPEÑO EXCELENTE, PROMEDIO GENERAL DE 95 A 100', 1);

INSERT INTO ALTERNATIVA(ALTERNATIVA, hab)
VALUES('PARTICIPACIÓN EN EVENTO ACADÉMICO NACIONAL', 1);

INSERT INTO ALTERNATIVA(ALTERNATIVA, hab)
VALUES('TESTIMONIO DE DESEMPEÑO SOBRESALIENTE (EGEL-CENEVAL)', 1);

-- Opciones

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('EGEL-CENEVAL', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('INTEGRADA', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('INTEGRAL', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('I TESIS PROFESIONAL', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('II LIBRO DE TEXTO O PROTOTIPO DIDÁCTICO', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('III PROYECTO DE INVESTIGACIÓN', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('IV DISEÑO O REDISEÑO DE EQUIPO, APARATO O MAQUINARIA', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('V CURSO ESPECIAL DE TITULACIÓN', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('VI EXAMEN GLOBAL POR ÁREAS DEL CONOCIMIENTO', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('VII MEMORIA DE EXPERIENCIA PROFESIONAL', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('VIII ESCOLARIDAD POR PROMEDIO', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('IX ESCOLARIDAD POR ESTUDIOS DE POSGRADO', 1);

INSERT INTO OPCIONES(OPCION, HAB)
VALUES('X MEMORIA DE RESIDENCIAS PROFESIONALES', 1);

-- Productos

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('EGEL-CENEVAL', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('INFORME DE ESTANCIA', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('INFORME TÉCNICO DE RESIDENCIA PROFESIONAL', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO DE EMPRENDEDURISMO', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO DE INNOVACIÓN TECNOLÓGICA', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO DE INVESTIGACIÓN', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO DE INVESTIGACIÓN Y/O DESARROLLO TECNOLÓGICO', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO INTEGRADOR', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO INTEGRAL DE EDUCACIÓN DUAL', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('PROYECTO PRODUCTIVO', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('RESIDENCIA PROFESIONAL', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('TESINA', 1);

INSERT INTO PRODUCTO(PRODUCTO, HAB)
VALUES('TESIS', 1);


